# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false

spring.datasource.url=jdbc:postgresql://localhost:5436/server2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# SSL / Server
server.port=8444
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=secret
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myserver

# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.topic=db-changes
kafka.group-id=db-sync-group

# Kafka Connect Configuration
kafka.connect.group-id=connect-cluster
kafka.connect.config.storage.topic=connect-configs
kafka.connect.offset.storage.topic=connect-offsets
kafka.connect.status.storage.topic=connect-status
kafka.connect.key.converter=org.apache.kafka.connect.json.JsonConverter
kafka.connect.value.converter=org.apache.kafka.connect.json.JsonConverter
kafka.connect.key.converter.schemas.enable=false
kafka.connect.value.converter.schemas.enable=false
kafka.connect.plugin.path=/usr/local/share/kafka/plugins

# Debezium Server 1 Configuration
debezium.server1.host=localhost
debezium.server1.port=5436
debezium.server1.database=server2
debezium.server1.user=admin
debezium.server1.password=admin

# Debezium Server 2 Configuration
debezium.server2.host=localhost
debezium.server2.port=5436
debezium.server2.database=server1
debezium.server2.user=admin
debezium.server2.password=admin

# Debezium: server1 = server2 (??????)
debezium.server1.slot.name=debezium_slot_server2
debezium.server1.database.server.name=server2
debezium.server1.topic.prefix=server2

# Debezium: server2 = server1 (??????)
debezium.server2.slot.name=debezium_slot_server1
debezium.server2.database.server.name=server1
debezium.server2.topic.prefix=server1
sync.origin=SERVER2

# === Debezium SMT: ????????? ????? sync_origin ===
debezium.transforms=identifySource
debezium.transforms.identifySource.type=org.apache.kafka.connect.transforms.InsertField$Value
debezium.transforms.identifySource.static.field=sync_origin
debezium.transforms.identifySource.static.value=SERVER2